# 🔢 NumPy for Machine Learning

This notebook provides a deep dive into NumPy with focus on functions most useful for machine learning tasks.

## 1. Introduction to NumPy
- Fast numerical operations
- Efficient array computations
- Backbone of ML libraries like Pandas, Scikit-learn, TensorFlow

### Importing NumPy:

In [1]:
import numpy as np

## 2. Creating Arrays
- `np.array()`
- `np.zeros()`, `np.ones()`, `np.full()`
- `np.arange()`, `np.linspace()`
- `np.random.*`

### Examples:

In [9]:
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((3, 2))
d = np.full((2, 2), 7)
e = np.arange(0, 10, 2)
f = np.linspace(0, 1, 5)
g = np.random.rand(2, 3)
a, b, c, d, e, f, g

(array([1, 2, 3]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7],
        [7, 7]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0.47724222, 0.61594705, 0.43170862],
        [0.23002104, 0.53550454, 0.37658918]]))

## 3. Array Attributes
- `shape`, `ndim`, `dtype`, `size`

In [12]:
arr = np.random.randint(0, 10, size=(3, 4))
print(arr)
arr.shape, arr.ndim, arr.dtype, arr.size

[[0 0 4 7]
 [2 7 8 4]
 [4 8 5 2]]


((3, 4), 2, dtype('int32'), 12)

## 4. Indexing and Slicing
- Access elements and subarrays

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1, 2], arr[:, 1], arr[0, :2]

(np.int64(6), array([2, 5]), array([1, 2]))

## 5. Array Operations
- Arithmetic: `+`, `-`, `*`, `/`
- Comparison: `>`, `<`, `==`
- Logical: `np.any`, `np.all`
- Broadcasting

In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y, y * 2, x > 1, np.any(x > 2), np.all(x > 0)

(array([5, 7, 9]),
 array([ 8, 10, 12]),
 array([False,  True,  True]),
 np.True_,
 np.True_)

## 6. Aggregation Functions
- `np.sum`, `np.mean`, `np.std`, `np.min`, `np.max`, `np.percentile`
- Axis-based aggregation

In [20]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data.sum(), data.mean(axis=0), data.std(), np.percentile(data, 50)

(np.int64(21),
 array([2.5, 3.5, 4.5]),
 np.float64(1.707825127659933),
 np.float64(3.5))

## 7. Reshaping and Stacking
- `reshape`, `ravel`, `flatten`
- `vstack`, `hstack`, `concatenate`

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.reshape(x, (4,))
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b)), np.hstack((a, b)), y

(array([[1, 2],
        [3, 4]]),
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4]))

## 8. Linear Algebra (Used in ML)
- `dot`, `matmul`, `transpose`, `inv`, `det`, `eig`
- Solving equations: `np.linalg.solve()`

In [21]:
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 13])
x = np.linalg.solve(A, B)
x

array([2.2, 3.6])

## 9. Random Module
- `rand`, `randn`, `randint`, `shuffle`, `choice`, `seed`

In [22]:
np.random.seed(42)
np.random.rand(3), np.random.randint(0, 10, 5), np.random.choice([10, 20, 30], 2)

(array([0.37454012, 0.95071431, 0.73199394]),
 array([4, 6, 9, 2, 6], dtype=int32),
 array([30, 30]))